### ISSUE TITLE
Dataset without train part

### ISSUE THREAD

**Issue by hi-zhengcheng** [Lilac-Lee/Neural_Scene_Flow_Prior#5]
Hi @Lilac-Lee:
interesting paper.

In paper's table 1, it says that 

> nuScenes Scene Flow
> Train: 1,513 samples, Test: 310 samples
>
> Argoverse Scene Flow
> Train: 2,691 samples, Test: 212 samples

Following the download link given in this repository, it seems that only **val** part is included in these two datasets. Could you also provide the download link for the **train** part or some instructions to download this kind of data? It will be appreciated if the **train** part is also included.

**Comment by Lilac-Lee** [comment]
Hi, our method did not use any training data. And these real-world autonomous driving scenes do not have ground truth for scene flow. Table 1 only gives an idea of the original dataset split. Cheers.

**Comment by Szy-Young** [comment]
Hi @Lilac-Lee:
First thanks for sharing the wonderful work. 

For nuScenes & Argoverse Scene Flow dataset, I see you follow [45] to collect pseudo-ground-truth scene flow. Since [45] has not released the code, will you consider sharing your **implementation of data processing**? This would be very helpful for future **learning-based methods** to follow your work and compare with it on these two benchmarks.
