### ISSUE TITLE
Regarding nuScenes dataset used in this paper

### ISSUE THREAD

**Issue by MinkyoungCho** [Lilac-Lee/Neural_Scene_Flow_Prior#7]
Hello! I have been really impressed by your amazing work; thanks for your contributions!

I am now curious about how the nuScenes dataset was modified from the original one [here](https://www.nuscenes.org/nuscenes#download). 
Especially, when I downloaded the original dataset (**Trainval**, not mini), the PCD format is `.pcd.bin` but yours is `.npz`.
I saw below in the paper but I cannot get fully; can I know the exact process you did to the original dataset?

> We followed the data processing method in [45] to collect pseudo-ground-truth scene flow.

Thanks in advance!

**Comment by Lilac-Lee** [comment]
Hi, thanks for the suggestion. We have updated the code and README. You can find the preprocessing code in [preprocess_sf_argoverse.py](preprocess_sf_argoverse.py) and [preprocess_sf_nuscenes.py](preprocess_sf_nuscenes.py). Cheers!

**Comment by MinkyoungCho** [comment]
I sincerely thank you for sharing the code I asked for and your amazing work! Wish you luck.

**Comment by yanconglin** [comment]
hi @Lilac-Lee, 
Thank you for releasing the code.
Unfortunately, I am not able to re-generate the same nuscenes scene flow dataset using the provided script. 
There are only 150 generated samples vs 310 in the given dataset (google drive).  And the sample indices do not match either.
Could you please double check?  I would like to re-geneate the dataset because I need the ground plane which has been removed from the given dataset. 
Many thanks!

**Comment by Lilac-Lee** [comment]
Hi, we used validation dataset provided in the nuScenes trainval-1.0 dataset, and there are 310 samples.
